AllCops:
  Include:
    - "**/Rakefile"
    - "**/config.ru"
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "bin/**"

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Rails:
  Enabled: true